version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: meridian_bank_db
    environment:
      POSTGRES_DB: meridian_bank
      POSTGRES_USER: meridian
      POSTGRES_PASSWORD: meridian_dev
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schemas/source_systems:/docker-entrypoint-initdb.d/01_source
      - ./schemas/data_warehouse:/docker-entrypoint-initdb.d/02_warehouse
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meridian -d meridian_bank"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
